channels_config:
  - source: BoostVolt1
  - source: BoostVolt2
  - source: BoostCurr1(A)
    transform: "lambda x: x * 0.01"
    filter_vals: [327.67, 204.79]
  - source: Vbalance.Uref(V)
    transform: "lambda x: x * 0.01"
  - source: Iboost_PICtl.Out
    transform: "lambda x: x * 0.01"
  - source: dd1
    transform: "lambda x: x * 0.001"
  - source: dd2
    transform: "lambda x: 1 - x * 0.001"
  - source: InvFault
  - source: d
    transform: "lambda x: x * 0.001"
  - source: delta_D
    transform: "lambda x: x * 0.001"
  - source: "deltaT"
    # transform: "lambda x: x * 0.001"
  - source: "500"
  - source: igbtTemp
  - source: "7000"
  - source:
      expression: "BoostVolt1 - BoostVolt2"
      name: BoostVolt_diff
  - source:
      expression: "BoostVolt1 + BoostVolt2"
      name: BoostVolt_sum

draw_config:
  column_groups:
    - title: "Voltage of Capacitors"
      columns: ["BoostVolt1", "BoostVolt2"]
      # yaxis: [370, 430]
    - title: "Voltage Difference"
      columns: ["BoostVolt_diff"]
      yaxis: [-50, 50]
    - title: "Boost Voltage Sum"
      columns: ["BoostVolt_sum"]
      # yaxis: [740, 860]
    - title: "Inductor Current"
      columns: ["BoostCurr1(A)"]
    - title: "Control Output"
      columns: ["Iboost_PICtl.Out"]
    - title: "Duty Cycle"
      columns: ["dd1", "dd2"]
    - title: "Reference Voltage"
      columns: ["Vbalance.Uref(V)"]
    - title: "deltaT"
      columns: ["deltaT"]
  cols_per_row: 2
  start_time: 0
  end_time: 1000
  xaxis_interval: auto 

settings:
  fs: 20000.0
  header: 0x7EEE
  tail: 0x7FFF
